import { createClient } from '@connectrpc/connect'
import { UserService } from '@/gen/user/v1/user_pb'
import { CourseService } from '@/gen/course/v1/course_pb'
import { MaterialService } from '@/gen/material/v1/material_pb'
import { AssignmentService } from '@/gen/assignment/v1/assignment_pb'
import { DashboardService } from '@/gen/dashboard/v1/dashboard_pb'
import { ClassService } from '@/gen/class/v1/class_pb'
import { JurusanService } from '@/gen/jurusan/v1/jurusan_pb'
import { SchoolService } from '@/gen/school/v1/school_pb'
import { AttendanceService } from '@/gen/attendance/v1/attendance_pb'
import { PklService } from '@/gen/pkl/v1/pkl_pb'
import { ClassroomService } from '@/gen/classroom/v1/classroom_pb'
import { ParentService } from '@/gen/parent/v1/parent_pb'
import { transport } from './transport'

export const userClient = createClient(UserService, transport)
export const courseClient = createClient(CourseService, transport)
export const materialClient = createClient(MaterialService, transport)
export const assignmentClient = createClient(AssignmentService, transport)
export const dashboardClient = createClient(DashboardService, transport)
export const classClient = createClient(ClassService, transport)
export const jurusanClient = createClient(JurusanService, transport)
export const schoolClient = createClient(SchoolService, transport)
export const attendanceClient = createClient(AttendanceService, transport)
export const pklClient = createClient(PklService, transport)
export const classroomClient = createClient(ClassroomService, transport)
export const parentClient = createClient(ParentService, transport)
